language: python
python:
  - 2.7
  - 3.4
notifications:
  irc:
    channels: "irc.freenode.org#vanrees"
    on_success: change
  email: true
install:
  - python bootstrap.py
  - bin/buildout
script:
  - bin/test
after_success:
  - bin/coveralls
